---
title: "Version 6: Cluster first"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(ggmcmc)
library(dplyr)
library(gridExtra)
library(stringr)
library(fs)
library(devtools)
load_all(file.path("..", "code", "clone.tools"))
outdir <- file.path("..", "output", "cluster_variants_2.Rmd")
dir_create(outdir)
```

## Simulate data

```{r sim}
I <- 100; K <- 10; S <- 3
set.seed(123)
test.data <- simulateData2(I, K, S)
```

## Connect $\omega$ by cluster

```{r cluster_vafs, eval=FALSE}
##
## Cluster means and variances
##
W <- test.data$w[test.data$z, ]
meds   <- apply(W, 2, median)
slevels <- colnames(test.data$w)[order(meds, decreasing=TRUE)]
w2 <- test.data$w %>%
    as_tibble() %>%
    mutate(z=factor(1:K)) %>%
    gather("sample", "omega", -z) %>%
    mutate(sample=factor(sample, levels=slevels))
fig2 <- ggplot(w2, aes(sample, omega, group=z)) +
    geom_point(size=1,  aes(color=z)) +
    geom_line(aes(color=z)) +
    ylab(expression(omega)) +
    xlab("") +
    theme(axis.text.x=element_text(angle=45, hjust=1),
          panel.background=element_rect(fill="white", color="black"),
          legend.key=element_rect(fill="white", color="white")) +
    guides(color=guide_legend(title="Variant cluster\n(z)"))
fig2
```

# Bayesian model: cluster mutations

```{r JAGS}
jags.file <- file.path("..", "code", "w.jags")
inits <- list(".RNG.name" = "base::Wichmann-Hill", 
              ".RNG.seed" = 123)
params <- c("z", "w", "ystar")
n.iter = 10000
thin = 7
K <- 10
samps <- runMCMC(test.data,
                 K,
                 jags.file,
                 inits,
                 params,
                 n.iter,
                 thin)
chains <- ggs(samps) 
z.chain <- chains[grep("z", chains$Parameter), ]
w.chain <- chains[grep("w", chains$Parameter), ]
mcmc_w <- group_by(w.chain, Parameter) %>%
    summarize(mean=mean(value))
saveRDS(chains, file.path(outdir, "chains.rds"))
```

