---
title: "Cluster simulated data: 3 samples, 10 clusters, 120 mutations total "
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(ggmcmc)
library(dplyr)
library(gridExtra)
library(stringr)
library(fs)
library(devtools)
load_all(file.path("..", "code", "clone.tools"))
outdir <- file.path("..", "output", "cluster_variants_BIC_I120.Rmd")
dir_create(outdir)
```

## Simulate data

```{r sim}
I <- 120; K <- 10; S <- 3
set.seed(123)
input.data <- simulateData(I, K, S)
```

## Connect $\omega$ by cluster

```{r cluster_vafs, eval=FALSE}
##
## Cluster means and variances
##
W <- input.data$w[input.data$z, ]
meds   <- apply(W, 2, median)
slevels <- colnames(input.data$w)[order(meds, decreasing=TRUE)]
w2 <- input.data$w %>%
    as_tibble() %>%
    mutate(z=factor(1:K)) %>%
    gather("sample", "omega", -z) %>%
    mutate(sample=factor(sample, levels=slevels))
fig2 <- ggplot(w2, aes(sample, omega, group=z)) +
    geom_point(size=1,  aes(color=z)) +
    geom_line(aes(color=z)) +
    ylab(expression(omega)) +
    xlab("") +
    theme(axis.text.x=element_text(angle=45, hjust=1),
          panel.background=element_rect(fill="white", color="black"),
          legend.key=element_rect(fill="white", color="white")) +
    guides(color=guide_legend(title="Variant cluster\n(z)"))
fig2
```

# Bayesian model: cluster mutations

```{r JAGS}
jags.file <- file.path("..", "code", "w.jags")
inits <- list(".RNG.name" = "base::Wichmann-Hill", 
              ".RNG.seed" = 123)
params <- c("z", "w", "ystar")
n.iter = 10000
thin = 7

kToTest <- 5:15
samps.list <- list()
for(i in 1:length(kToTest)) {
  samps.list[[i]] <- runMCMC(input.data, kToTest[i], jags.file, inits, params, n.iter, thin)
}
saveRDS(samps.list, file.path(outdir, "samps.list.rds"))
```

```{r BIC}
BIC <- mapply(function(samps, k) calcBIC(I*S, k, calcChainLogLik(samps, input.data, k)), samps = samps.list, k = kToTest)
BIC

min.ind <- which(BIC == min(BIC))
min.BIC.tb <- tibble(k = kToTest[min.ind],
                     BIC = min(BIC))

BIC_tb <- tibble(k = kToTest,
                 BIC = BIC)
BIC.plot <- ggplot(BIC_tb, aes(x = k, y = BIC)) +
  geom_line() +
  theme_light() +
  scale_x_continuous(breaks = kToTest) +
  geom_point(data = min.BIC.tb, color = "blue", size = 3)
BIC.plot

ggsave(file.path(outdir, "BIC_k5to15.pdf"),
       BIC.plot)
```

```{r chains}
samps <- samps.list[[min.ind]]
chains <- ggs(samps)
saveRDS(chains, file.path(outdir, paste0("chains_K", kToTest[min.ind], ".rds")))
```