---
title: "IP30 analysis -- tree MH"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(ggmcmc)
library(gridExtra)
library(stringr)
library(fs)
library(devtools)
library(tidyverse)
library(ggnet)
library(network)
library(sna)
devtools::load_all(file.path("..", "code", "clone.tools"))

outdir <- file.path("..", "output", "IP30_2.Rmd")
dir_create(outdir)

data.dir <- file.path("..", "data")

```

## Clustering data
```{r}
samps.list <- readRDS(file.path(outdir, "samps.list.rds"))
K <- 12
kToTest <- 5:15
samps <- samps.list[[which(kToTest == K)]] 
chains <- ggs(samps) 

z.chain <- chains[grep("z", chains$Parameter), ]
w.chain <- chains[grep("w", chains$Parameter), ]

mcf_stats <- w.chain %>%
    group_by(Parameter) %>%
    summarize(sd=sd(value),
              mean=mean(value))
```

# MH-sampler for tree

```{r tree_mcmc}
set.seed(1234)

# Initialize chain ------------------------------------------------------------

admat.chain <- list(rand.admat(initializeAdjacencyMatrix(mcf_stats = mcf_stats, zero.thresh = 0.01)))
sampled.w.chain <- list(sample.w(w.chain, K))
cpov.chain <- list(create.cpov(mcf_stats = mcf_stats, mcf_matrix = sampled.w.chain[[1]]))
score.chain <- calc.tree.fitness(admat.chain[[1]], cpov.chain[[1]], sampled.w.chain[[1]])


# MCMC ------------------------------------------------------------------------

numAccept  <-  0
ncol.to.mutate <- 1
numIter <- 10000

for (i in seq_len(numIter)) {
    fit.prev <- score.chain[i]

    ##
    ## Propose edge
    ##
    admat.star <- mutate.admat(admat.chain[[i]], ncol.to.mutate)
    #proposed <- plotDAG(admat.star)
    sampled.w.star <- sample.w(w.chain, K)
    cpov.star <- create.cpov(mcf_stats, mcf_matrix = sampled.w.star)
    fit.star <- calc.tree.fitness(admat.star, cpov.star, sampled.w.star)
    
    r <- fit.star / fit.prev
    u <- runif(1, 0, 1)    
    if(u <= r) {
        admat.chain[[i+1]] <- admat.star
        numAccept <- numAccept + 1
        score.chain <- c(score.chain, fit.star)
        cpov.chain[[i+1]] <- cpov.star
        sampled.w.chain[[i+1]] <- sampled.w.star
    } else {
        admat.chain[[i+1]] <- admat.chain[[i]]
        score.chain <- c(score.chain, fit.prev)
        cpov.chain[[i+1]] <- cpov.chain[[i]]
        sampled.w.chain[[i+1]] <- sampled.w.chain[[i]]
    }
}
results <- list(admat.chain=admat.chain,
                score.chain=score.chain,
                cpov.chain=cpov.chain,
                sampled.w.chain=sampled.w.chain,
                numAccept=numAccept)

acceptRate <- numAccept/numIter
acceptRate

saveRDS(results, file.path(outdir, "trees.rds"))
```

```{r thin}
# Thin ------------------------------------------------------------------------
thin <- 10

thin_chain <- function(thin, x) {
  if (thin > 1) {
    # keep only thinned rows
    x_thinned <- x[(seq_len(length(x)) %% thin) == 1]
  } else {
    x_thinned <- x
  }
  x_thinned
}

score.chain.thinned <- thin_chain(thin, score.chain)

plot(score.chain.thinned)
plot(log(score.chain.thinned))

thinned.tb <- tibble(score = score.chain.thinned, 
                     iter = seq_len(length(score.chain.thinned)),
                     log.score = log(score.chain.thinned))

ggplot(thinned.tb, aes(x = iter, y = log.score)) +
  geom_line() +
  theme_light()

admat.chain.thinned <- thin_chain(thin, admat.chain)
score.chain.thinned <- thin_chain(thin, score.chain)
```

```{r post}
##
## posterior distribution of trees
##
numericRepresentation <- function(x){
    x[is.na(x)] <- 0
    x <- as.numeric(x)
    paste(x, collapse="")
}
trees <- sapply(admat.chain.thinned, numericRepresentation)
tab <- table(trees)
length(tab)
freq <- as.numeric(tab)
prob <- freq/(numIter/thin)
plot(prob)
#tab2 <- tab[prob > 0.01]

max(score.chain.thinned)
max.score.ind <- which(score.chain.thinned == max(score.chain.thinned))
if(length(max.score.ind) > 1) max.score.ind <- max.score.ind[1]
max.admat <- admat.chain.thinned[[max.score.ind]]
max.admat

plotDAG(max.admat)

mostFreqTree <- names(tab[which(max(prob) == prob)])
mostFreqAdmat <- admat.chain.thinned[[which(mostFreqTree[1] == trees)[1]]]
plotDAG(mostFreqAdmat)
```
