---
title: "IP30 analysis -- tree MH"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(ggmcmc)
library(gridExtra)
library(stringr)
library(fs)
library(devtools)
library(tidyverse)
library(GGally)
library(network)
library(sna)
devtools::load_all(file.path("..", "code", "clone.tools"))

outdir <- file.path("..", "output", "IP30_weighted_mutate.Rmd")
dir_create(outdir)

data.dir <- file.path("..", "data")

```

## Clustering data
```{r}
# samps.list <- readRDS(file.path("..", "output", "IP30_spikenslab.Rmd", "samps.list.rds"))
# K <- 21
# kToTest <- 15:25
# samps <- samps.list[[which(kToTest == K)]] 
# chains <- ggs(samps) 

K <- 21
chains <- readRDS(file.path("..", "output", "IP30_spikenslab.Rmd", paste0("chains_K", K, ".rds")))


z.chain <- chains[grep("z\\[", chains$Parameter), ]
w.chain <- chains[grep("w", chains$Parameter), ]


K <- 20
# remove cluster4
new.w.chain <- w.chain %>%
  mutate(k = as.numeric(gsub("w\\[", "", sapply(w.chain$Parameter, function(x) strsplit(as.character(x), ",")[[1]][1])))) %>%
  mutate(s = gsub("\\]", "", sapply(w.chain$Parameter, function(x) strsplit(as.character(x), ",")[[1]][2])))
# relabel clusters 5-21 to 4-20
new.w.chain <- new.w.chain %>% 
  filter(k != 4) %>%
  mutate(k = ifelse(k>3, k-1, k))
# change parameter 
new.w.chain <- new.w.chain %>%
  mutate(Parameter = factor(paste0("w[", k, ",", s, "]"), levels = levels(w.chain$Parameter)))

new.z.chain <- z.chain %>%
  mutate(value = ifelse(value>3, value-1, value))

w.chain <- new.w.chain
z.chain <- new.z.chain

saveRDS(w.chain, file.path("..", "output", "IP30_spikenslab_2.Rmd", paste0("w_chain_K", K, "_fixedfromK21.rds")))
saveRDS(z.chain, file.path("..", "output", "IP30_spikenslab_2.Rmd", paste0("z_chain_K", K, "_fixedfromK21.rds")))

mcf_stats <- w.chain %>%
    group_by(Parameter) %>%
    summarize(sd=sd(value),
              mean=mean(value))
```

# MH-sampler for tree

```{r tree_mcmc}
seed = 2
set.seed(seed)

# Initialize chain ------------------------------------------------------------

admat.chain <- list(rand.admat(initializeAdjacencyMatrix(mcf_stats = mcf_stats, zero.thresh = 0.01)))
sampled.w.chain <- list(sample.w(w.chain, K))
cpov.chain <- list(create.cpov(mcf_stats = mcf_stats, mcf_matrix = sampled.w.chain[[1]]))
score.chain <- calc.tree.fitness(admat.chain[[1]], cpov.chain[[1]], sampled.w.chain[[1]])


# MCMC ------------------------------------------------------------------------

numAccept  <-  0
ncol.to.mutate <- 1
numIter <- 50000

for (i in seq_len(numIter)) {
    fit.prev <- score.chain[i]

    ##
    ## Propose edge
    ##
    admat.star <- mutate.admat.3(admat.chain[[i]], ncol.to.mutate, sampled.w.chain[[i]])
    #proposed <- plotDAG(admat.star)
    sampled.w.star <- sample.w(w.chain, K)
    cpov.star <- create.cpov(mcf_stats, mcf_matrix = sampled.w.star)
    fit.star <- calc.tree.fitness(admat.star, cpov.star, sampled.w.star)
    
    r <- fit.star / fit.prev
    u <- runif(1, 0, 1)    
    if(u <= r) {
        admat.chain[[i+1]] <- admat.star
        numAccept <- numAccept + 1
        score.chain <- c(score.chain, fit.star)
        cpov.chain[[i+1]] <- cpov.star
        sampled.w.chain[[i+1]] <- sampled.w.star
    } else {
        admat.chain[[i+1]] <- admat.chain[[i]]
        score.chain <- c(score.chain, fit.prev)
        cpov.chain[[i+1]] <- cpov.chain[[i]]
        sampled.w.chain[[i+1]] <- sampled.w.chain[[i]]
    }
}


acceptRate <- numAccept/numIter
acceptRate


```


```{r}
results <- list(admat.chain=admat.chain,
                score.chain=score.chain,
                cpov.chain=cpov.chain,
                sampled.w.chain=sampled.w.chain,
                numAccept=numAccept)
saveRDS(results, file.path(outdir, paste0("trees_50k_notThinned_K", K ,"_seed", seed, ".rds")))
```

```{r }
thin <- 10

thin.ind <- seq(1, numIter, length.out = round(numIter/thin, 1))

score.chain.thinned <- results$score.chain[thin.ind]

thinned.tb <- tibble(score = score.chain.thinned, 
                     iter = seq_len(length(score.chain.thinned)),
                     log.score = log(score.chain.thinned))

ggplot(thinned.tb, aes(x = iter, y = log.score)) +
  geom_line() +
  theme_light()
ggsave(file.path(outdir, paste0("log_score_chain_K", K, "_seed", seed, ".pdf")), width = 7, height = 4)

```
