---
title: "IP30 analysis -- cluster variants & BIC"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(ggmcmc)
library(gridExtra)
library(stringr)
library(fs)
library(devtools)
library(tidyverse)
library(GGally)
library(network)
library(sna)
devtools::load_all(file.path("..", "code", "clone.tools"))

outdir <- file.path("..", "output", "IP30_spikenslab.Rmd")
dir_create(outdir)

data.dir <- file.path("..", "data")

```

## IP30 data

```{r data}
data.file <- file.path(data.dir, "IP30_test_input.tsv")
mut.data <- read.table(data.file, sep = "\t", header = T, stringsAsFactors = F) %>%
  as_tibble()

y <- mut.data %>%
  select(sample, mut_id, y) %>%
  spread(sample, y)

n <- mut.data %>%
  select(sample, mut_id, n) %>%
  spread(sample, n)

m <- mut.data %>%
  select(sample, mut_id, m) %>%
  spread(sample, m)
m[m == 0] <- 1

tcn <- mut.data %>%
  select(sample, mut_id, tcn) %>%
  spread(sample, tcn)

S <- length(unique(mut.data$sample))
I <- length(unique(mut.data$mut_id))

input.data <- list("I" = I, "S" = S,
                   "y" = y[, 2:(S+1)], "n" = n[, 2:(S+1)],
                   "m" = m[, 2:(S+1)], "tcn" = tcn[, 2:(S+1)])
```

## Check input
```{r}
all(input.data$tcn > 0)
all(input.data$tcn >= input.data$m)
all.equal(which(input.data$m == 0), which(input.data$y == 0))
```

## Cluster variants, BIC

```{r cluster}
set.seed(1234)
jags.file <- file.path("..", "code", "spike_and_slab.jags")
inits <- list(".RNG.name" = "base::Wichmann-Hill", 
              ".RNG.seed" = 123)
params <- c("z", "w", "ystar", "z.p")
n.iter = 1000
thin = 7

kToTest <- 5:20
samps.list <- list()
for(i in 1:length(kToTest)) {
  samps.list[[i]] <- runMCMC(input.data, kToTest[i], jags.file, inits, params, n.iter, thin)
}
saveRDS(samps.list, file.path(outdir, "samps.list.rds"))

BIC <- mapply(function(samps, k) calcBIC(I*S, k, calcChainLogLik(samps, input.data, k)), samps = samps.list, k = kToTest)
BIC

BIC_tb <- tibble(k = kToTest,
                 BIC = BIC)
min.ind <- which(BIC == min(BIC))
min.BIC.tb <- tibble(k = kToTest[min.ind],
                     BIC = min(BIC))
BIC.plot <- ggplot(BIC_tb, aes(x = k, y = BIC)) +
  geom_line() +
  theme_light() +
  scale_x_continuous(breaks = kToTest) +
  geom_point(data = min.BIC.tb, color = "blue", size = 3)
BIC.plot

ggsave(file.path(outdir, paste0("IP30_BIC_k", kToTest[1], "to", kToTest[length(kToTest)],".pdf")),
       BIC.plot)

best <- which.min(BIC)
best.k <- kToTest[best]
```
