---
title: "Version 3: 4 clusters"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(MCMCpack)
#library(bayesplot)
library(ggmcmc)
library(dplyr)
library(gridExtra)

working.dir <- "~/Dropbox/Wood-Collab-Progression/clustering/v3"
models.dir <- file.path(working.dir, "models")
trace.dir <- file.path(working.dir, "trace")
#dir.create(trace.dir, showWarnings = F)
runName <- "w_K4"
```

## Simulate data

```{r sim}
I <- 50
K <- 4
S <- 10

# choose diffuse priors for gamma
a_gamma <- 2
b_gamma <- 10

set.seed(123)

a <- matrix(NA, nrow=K, ncol=S)
b <- matrix(NA, nrow=K, ncol=S)
for (s in 1:S) {
  a[, s] <- rgamma(K, a_gamma, rate = 1/b_gamma)
  b[, s] <- rgamma(K, a_gamma, rate = 1/b_gamma)
}
colnames(a) <- colnames(b) <- paste0("sample", seq_len(ncol(a)))
# reorder a,b matrices to match ordering of means (U) in S1
U <- a/(a+b)
V <- a+b
ix <- order(U[, 1])
U.ordered <- U[ix, ]
a.ordered <- a[ix, ]
b.ordered <- b[ix, ]
V.ordered <- V[ix, ]

#pi <- as.vector(rdirichlet(1, rep(1, K)))
pi <- c(0.2, 0.3, 0.2, 0.3)
z <- sample(1:K, size = I, replace = T, prob = pi)

##
## omega (w) is the cancer cell fraction
## - shouldn't omega have dimension K x S
## - I'd like to be able to recover the true values of a and b
## ->  a single random ordinate drawn from this distribution
##     might not be representative
##     a an average over 1000 random ordinates guarantees that
##     we have a representative ordinate of beta(a, b)
w <- matrix(NA, nrow=K, ncol=S)
for(k in seq_len(K)){
    tmp <- rowMeans(replicate(1000,
                              rbeta(S, a.ordered[k, ],
                                    b.ordered[k, ])))
    w[k, ] <- tmp
}

tcn <- matrix(2, nrow=I, ncol=S)
m <- matrix(rep(sample(1:2, size = I, replace = T), S), 
            nrow=I, ncol=S)
W <- w[z, ]
calcTheta <- function(m, tcn, w) {
  (m * w) / (tcn * w + 2*(1-w))
}
theta <- calcTheta(m, tcn, W)

n <- replicate(S, rpois(I, 100))
y <- matrix(NA, nrow=I, ncol=S)
for (i in 1:I) {
  for (s in 1:S) {
    y[i, s] <- rbinom(1, n[i, s], theta[i,s])
  }
}

test.data <- list("I" = I, "S" = S, "K" = K, 
                  "y" = y, "n" = n,
                  "m" = m, "tcn" = tcn)
```
# Visualize densities of simulated data

Clustering is by $\omega$

```{r simulated_densities}
test.data <- list("I" = I, "S" = S, "K" = K,
                  "y" = y, "n" = n,
                  "m" = m, "tcn" = tcn)
p <- test.data$y/test.data$n
colnames(w) <- colnames(p) <- paste0("sample", seq_len(ncol(p)))
colnames(m) <- colnames(p)
m2 <- m %>%
    as_tibble() %>%
    mutate(z=factor(z),
           variant_index=seq_len(nrow(.))) %>%
    gather("sample", "multiplicity", -c(z, variant_index)) %>%
    mutate(sample=factor(sample, levels=colnames(p)))
p2 <- p %>%
    as_tibble() %>%
    mutate(z=factor(z),
           variant_index=seq_len(nrow(.))) %>%
    gather("sample", "fraction", -c(z, variant_index)) %>%
    mutate(sample=factor(sample, levels=colnames(p))) %>%
    left_join(m2, by=c("z", "variant_index", "sample")) %>%
    mutate(multiplicity=factor(multiplicity))
## what the data looks like by sample
ggplot(p2, aes(z, fraction)) +
    geom_jitter(width=0.1, size=1, aes(color=multiplicity)) +
    facet_wrap(~sample) +
    ylab("y/n") +
    xlab("True cluster") +
    theme(panel.background=element_rect(fill="white", color="black"))
## by variant
ggplot(p2, aes(sample, fraction, group=variant_index)) +
    geom_point(size=1) +
    geom_line(aes(color=z)) +
    ylab("y/n") +
    xlab("Patient sample\n(arbitrary order)") +
    theme(axis.text.x=element_text(angle=45, hjust=1)) +
    guides(color=guide_legend(title="Variant cluster\n(z)"))
##
## Cluster means and variances
##
meds   <- apply(W, 2, median)
slevels <- colnames(w)[order(meds, decreasing=TRUE)]
w2 <- w %>%
    as_tibble() %>%
    mutate(z=factor(1:K)) %>%
    ##       variant_index=seq_len(nrow(.))) %>%
    gather("sample", "omega", -z) %>%
    mutate(sample=factor(sample, levels=slevels))
##fig1 <- ggplot(w2, aes(z, omega)) +
##    geom_jitter(width=0.1, size=1) +
##    facet_wrap(~sample) +
##    ylab(expression(omega)) +
##    xlab("True cluster") +
##    theme(panel.background=element_rect(fill="white", color="black"))
fig2 <- ggplot(w2, aes(sample, omega, group=z)) +
    geom_point(size=1,  aes(color=z)) +
    geom_line(aes(color=z)) +
    ylab(expression(omega)) +
    xlab("") +
    theme(axis.text.x=element_text(angle=45, hjust=1),
          panel.background=element_rect(fill="white", color="black"),
          legend.key=element_rect(fill="white", color="white")) +
    guides(color=guide_legend(title="Variant cluster\n(z)"))
fig2
```

## JAGS

```{r JAGS}
jags.file <- file.path(models.dir, "w.jags")
inits <- list(".RNG.name" = "base::Wichmann-Hill", 
              ".RNG.seed" = 123)
jags.m <- jags.model(jags.file, test.data,
                     n.chains = 1,
                     inits = inits,
                     n.adapt = 1000)
params <- c("z", "w", "ystar")
samps <- coda.samples(jags.m, params, n.iter=10000, thin=7)
jags_df <- ggs(samps)
##ggs_traceplot(jags_df, family="U")
s <- summary(samps)
#effectiveSize(samps)
#pdf(file.path(trace.dir, paste0(runName, "_trace.pdf")))
#plot(samps)
#dev.off()
```
```{r res}
##
## 50 mutations x 10 samples
chains <- do.call(rbind, samps)
ystar <- chains[, grep("ystar", colnames(chains))]
## each row of MCMC is in column-major order
orig.order <- tibble(statistic=colnames(ystar))
ppd.summaries <- ystar %>%
    as_tibble() %>%
    gather("statistic", "value") %>%
    group_by(statistic) %>%
    summarize(mean=mean(value),
              q1=quantile(value, 0.025),
              q3=quantile(value, 0.975))
ppd.summaries2 <- left_join(orig.order,
                            ppd.summaries, by="statistic") %>%
    mutate(observed=as.numeric(test.data$y)) %>%
    mutate(sample=paste0("sample", rep(1:S, each=I)),
           variant=rep(1:I, S))
ggplot(ppd.summaries2, aes(x=statistic, y=mean,
                           ymin=q1,
                           ymax=q3)) +
    geom_errorbar() +
    geom_point(aes(x=statistic, y=observed),
               size=1, color="steelblue") +
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          panel.background=element_rect(fill="white",
                                        color="black")) +
    ylab("Middle 95% of posterior\npredictive distribution") +
    xlab("observation index (column-major order)") +
    facet_wrap(~sample)
```

## Plots

```{r z, echo=F}
mcmc_vals <- s$statistics
mcmc_z <- as.vector(mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "z", "Mean"])
plot(z, mcmc_z, type = "p")
z_comp <- data.frame(z, mcmc_z)
z_mapping <- distinct(z_comp)
z_mapping <- z_mapping[order(z_mapping$z), ]
plot.new()
grid.table(z_mapping, rows=NULL)
```

```{r w, echo=F}
mcmc_w <- mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "w", "Mean"]
mcmc_w <- matrix(mcmc_w, nrow=K)
colnames(mcmc_w) <- paste0("sample", 1:S)
mcmc_w2 <- mcmc_w %>%
  as_tibble() %>%
  mutate(cluster=z_mapping$mcmc_z) %>%
  gather("sample", "mcmc_w", -c(cluster))
w_comp <- w %>%
  as_tibble() %>%
  mutate(cluster=1:K) %>%
  gather("sample", "w", -c(cluster)) %>%
  left_join(mcmc_w2, by=c("cluster", "sample")) %>%
  mutate(cluster=factor(cluster),
         sample=factor(sample))

# scatter
ggplot(w_comp, aes(w, mcmc_w)) +
  geom_point(size=3, aes(color=sample, shape=cluster)) +
  geom_abline(slope=1, intercept=0, linetype="dotted")

# by sample
w_comp2 <- w_comp %>% 
  gather("type", "omega", -c(cluster, sample)) %>%
  mutate(type=factor(type))
w_comp2$grp <- paste(w_comp2$cluster, w_comp2$type)
ggplot(w_comp2, aes(sample, omega, group=grp)) +
    geom_point(size=3,  aes(color=cluster)) +
    geom_line(aes(color=cluster, lty=type)) +
    ylab(expression(omega)) +
    xlab("") +
    theme(axis.text.x=element_text(angle=45, hjust=1),
          panel.background=element_rect(fill="white", color="black"),
          legend.key=element_rect(fill="white", color="white")) +
    guides(color=guide_legend(title="Variant cluster\n(z)"))
```

```{r betas, eval=F, echo=F}
mcmc_U <- mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "U", "Mean"]
mcmc_U <- matrix(mcmc_U, nrow=K)
colnames(mcmc_U) <- paste0("sample", 1:S)
mcmc_V <- mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "V", "Mean"]
mcmc_V <- matrix(mcmc_V, nrow=K)
colnames(mcmc_V) <- paste0("sample", 1:S)

mcmc_U2 <- mcmc_U %>%
    as_tibble() %>%
    mutate(cluster=z_mapping$mcmc_z,
           type="mcmc") %>%
    gather("sample", "U", -c(cluster, type)) %>%
    mutate(sample=factor(sample, levels=colnames(mcmc_U)))

mcmc_betas <- mcmc_V %>%
    as_tibble() %>%
    mutate(cluster=z_mapping$mcmc_z,
           type="mcmc") %>%
    gather("sample", "V", -c(cluster, type)) %>%
    mutate(sample=factor(sample, levels=colnames(mcmc_U))) %>%
    left_join(mcmc_U2, by=c("cluster", "type", "sample")) 
mcmc_betas$a <- mcmc_betas$U * mcmc_betas$V
mcmc_betas$b <- (1 - mcmc_betas$U) * mcmc_betas$V

a2 <- a.ordered %>%
    as_tibble() %>%
    mutate(cluster=1:K,
           type="truth") %>%
    gather("sample", "a", -c(cluster, type)) %>%
    mutate(sample=factor(sample, levels=colnames(a.ordered)))

true_betas <- b.ordered %>%
    as_tibble() %>%
    mutate(cluster=1:K,
           type="truth") %>%
    gather("sample", "b", -c(cluster, type)) %>%
    mutate(sample=factor(sample, levels=colnames(b.ordered))) %>%
    left_join(a2, by=c("cluster", "type", "sample")) 

betas <- bind_rows(true_betas, mcmc_betas)

dens_list <- list()
for(row.ix in 1:nrow(betas)) {
  x <- seq(0, 1, length = 100)
  val <- dbeta(x, shape1=betas[row.ix, ]$a, shape2=betas[row.ix, ]$b)
  dens_list[[row.ix]] <- data.frame(x=x, val=val, 
                                 type=betas[row.ix, ]$type,
                                 cluster=betas[row.ix, ]$cluster,
                                 sample=betas[row.ix, ]$sample,
                                 stringsAsFactors = F)
}

dens_df <- bind_rows(dens_list)
dens_df$grp <- paste0("k", dens_df$cluster, ",", dens_df$sample, ",", dens_df$type)
dens_df$cluster <- as.factor(dens_df$cluster)

## beta distributions by sample
beta.plot <- ggplot(dens_df, aes(x=x, y=val, group=grp)) +
  geom_line(aes(color=cluster, lty=type)) +
  facet_wrap(~sample) +
  ylab("density") +
  xlab("w") +
  theme(panel.background=element_rect(fill="white", color="black"))
beta.plot
```

```{r, echo=F, eval=FALSE}
samples_matrix <- as.matrix(samps)

U_chains <- samples_matrix[, which(substr(colnames(samples_matrix), 1, 1) == "U")]

pdf(file.path(working.dir, paste0(runName, "_Uplots.pdf")))
for (s in 1:S) {
  s.char <- paste(s)
  if (nchar(s.char) == 1) {
    U_sub <- U_chains[, which(substr(colnames(U_chains), 5, 6) == paste0(s.char, "]"))]
  } else {
    U_sub <- U_chains[, which(substr(colnames(U_chains), 5, 7) == paste0(s.char, "]"))]
  }
  plot(density(as.vector(U_sub)),
       main = paste0("S", s, " U density; K=", K))
  legend(x = "topright", 
         legend = paste0("k", 1:K, ", true U = ", round(U[,s], 2)))
}
dev.off()

pdf(file.path(working.dir, paste0(runName, "_Uplots_withTruth.pdf")))
for (s in 1:S) {
  s.char <- paste(s)
  if (nchar(s.char) == 1) {
    U_sub <- U_chains[, which(substr(colnames(U_chains), 5, 6) == paste0(s.char, "]"))]
  } else {
    U_sub <- U_chains[, which(substr(colnames(U_chains), 5, 7) == paste0(s.char, "]"))]
  }
  plot(density(as.vector(U_sub)),
       main = paste0("S", s, " U density; K=", K))
  legend(x = "topright", 
         legend = paste0("k", 1:K, ", true U = ", round(U[,s], 2)),
         col = colors[1:K],
         lty = "dashed")
  u <- round(U[,s], 2)
  for ( i in 1:length(u)) {
    abline(v = u[i], col = colors[i], lty = "dashed")
  }
  
}
dev.off()
```
