---
title: "Version 2: 2 clusters; Fix cluster label switching  \n u,v; unif; fix w [0,1]; only force ordering of means in 1 sample; S4"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(MCMCpack)
library(bayesplot)

working.dir <- "~/Dropbox/Wood-Collab-Progression/clustering/v2"
models.dir <- file.path(working.dir, "models")
trace.dir <- file.path(working.dir, "trace")
dir.create(trace.dir, showWarnings = F)
runName <- "v2_uv_unif_S4"
```

## Simulate data

```{r sim}
I <- 50
K <- 2
S <- 10

# choose diffuse priors for gamma
a_gamma <- 2
b_gamma <- 10

avrg <- a_gamma * b_gamma
std.dv <- sqrt(a_gamma*b_gamma^2)
g_range = seq(0, avrg + 5*std.dv, 0.01)
g_y = dgamma(g_range, a_gamma, rate = 1/b_gamma)
#plot(g_range, g_y, type = "l", ylim=c(0, max(g_y) + 0.01))

set.seed(123)

a <- matrix(NA, nrow=K, ncol=S)
b <- matrix(NA, nrow=K, ncol=S)
for (s in 1:S) {
  a[, s] <- rgamma(K, a_gamma, rate = 1/b_gamma)
  b[, s] <- rgamma(K, a_gamma, rate = 1/b_gamma)
}

# reorder a,b matrices to match ordering of means (U) in S1
U <- a/(a+b)
V <- a+b
U.ordered <- U[order(U[,1]), ]
a.ordered <- a[order(U[,1]), ]
b.ordered <- b[order(U[,1]), ]
V.ordered <- V[order(U[,1]), ] 

pi <- as.vector(rdirichlet(1, rep(1, K)))
z <- sample(1:K, size = I, replace = T, prob = pi)

w <- matrix(NA, nrow=I, ncol=S)
for (s in 1:S) {
  w[, s] <- rbeta(I, a.ordered[,s][z], b.ordered[,s][z])
}

tcn <- matrix(2, nrow=I, ncol=S)
m <- matrix(rep(sample(1:2, size = I, replace = T), S), nrow=I, ncol=S)

calcTheta <- function(m, tcn, w) {
  (m * w) / (tcn * w + 2*(1-w))
}
theta <- calcTheta(m, tcn, w)

n <- replicate(S, rpois(I, 100))
y <- matrix(NA, nrow=I, ncol=S)
for (i in 1:I) {
  for (s in 1:S) {
    y[i, s] <- rbinom(1, n[i, s], theta[i,s])
  }
}

#n_S2 <- subset(n, select = 2)
#y_S2 <- subset(y, select = 2)
#m_S2 <- subset(m, select = 2)
#tcn_S2 <- subset(tcn, select = 2)
n_S4 <- n[ , 4]
y_S4 <- y[ , 4]
m_S4 <- m[ , 4]
tcn_S4 <- tcn[ , 4]
w_S4 <- w[ ,4]
S <- 1
```

## JAGS

```{r JAGS}
jags.file <- file.path(models.dir, "v2_uv_unif_fix2_1sample.jags")

test.data <- list("I" = I, "K" = K, 
                  "y" = y_S4, "n" = n_S4,
                  "m" = m_S4, "tcn" = tcn_S4)
jags.m <- jags.model(jags.file, test.data,
                     n.chains = 1,
                     inits = list(".RNG.name" = "base::Wichmann-Hill", 
                                  ".RNG.seed" = 123))
params <- c("z", "w", "U", "V")
samps <- coda.samples(jags.m, params, n.iter=6000, thin = 6)
s <- summary(samps)
effectiveSize(samps)
pdf(file.path(trace.dir, paste0(runName, "_trace.pdf")))
plot(samps)
dev.off()
```

```{r plots}
mcmc_vals <- s$statistics
mcmc_w <- mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "w", "Mean"]
plot(as.vector(w_S4), mcmc_w, type = "p")
abline(a=0, b=1)

mcmc_z <- as.vector(mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "z", "Mean"])
#mcmc_z <- round(mcmc_z, 0)
plot(z, mcmc_z, type = "p")

mcmc_U <- mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "U", "Mean"]
mcmc_U <- matrix(mcmc_U, nrow=K)
mcmc_V <- mcmc_vals[substr(rownames(mcmc_vals), 1, 1) == "V", "Mean"]
mcmc_V <- matrix(mcmc_V, nrow=K)

mcmc_U

p <- seq(0, 1, length = 100)
colors <- c("#000000", "#DCA200", "#8FA7ED", "#9D847A", "#A47901")
for (k in 1:K) {
  if (k == 1) {
    # plot mcmc mean U,V
    plot(p, dbeta(p, mcmc_U[k] * mcmc_V[k], (1-mcmc_U[k])*mcmc_V[k]), 
         main = "S4", 
         ylab = "density", xlab = "w", type = "l", col = colors[k],
         ylim = c(0, 12))
    # plot truth
    lines(p, dbeta(p, a.ordered[k,4], b.ordered[k,4]), type = "l", col = colors[k], lty=2)
    # add legend
    legend(x = "topleft", 
           legend = paste0(c("mcmc k", "true k"), rep(1:K, each=2)),
           col = colors[rep(1:K, each=2)],
           lty = rep(1:2, K),
           cex=0.8)
  } else {
    # plot mcmc mean U,V
    lines(p, dbeta(p, mcmc_U[k] * mcmc_V[k], (1-mcmc_U[k])*mcmc_V[k]), 
          type = "l", col = colors[k])
    # plot truth
    lines(p, dbeta(p, a.ordered[k,4], b.ordered[k,4]), type = "l", col = colors[k], lty=2)
  }
}

U_trace <- samps[[1]][, 1:2]
V_trace <- samps[[1]][, 3:4]
traceplot(U_trace[,1], ylim = c(0,1))
traceplot(U_trace[,2], ylim = c(0,1))
traceplot(V_trace[,1], ylim = c(0,max(V_trace)+20))
traceplot(V_trace[,2], ylim = c(0,max(V_trace)+20))

x1 <- samps[[1]][, c(1,3)]
dimnames(x1)[[2]] <- c("U", "V")
x2 <- samps[[1]][, c(2,4)]
dimnames(x2)[[2]] <- c("U", "V")
UV_trace <- list(x1, x2)
mcmc_trace(UV_trace, regex_pars = c("U", "V"))
```
