---
title: "Untitled"
author: "Lester"
date: "2022-10-02"
output: html_document
---

```{r setup, include=FALSE}
library(pictograph)
library(tidyverse)
#devtools::load_all("~/GitHub/pictograph")
```

## Get the cluster info
```{r pressure, echo=FALSE}
input_data <- readRDS("C:/Users/Leste/OneDrive - Johns Hopkins/Desktop/Karchin Lab/data/pictograph-input/IP22_input_data.rds")

# all_set_results <- clusterSep(input_data,
#                               n.iter = 1000, n.burn = 100, thin = 1,
#                               max_K = 5)

all_set_results <- readRDS("C:/Users/Leste/OneDrive - Johns Hopkins/Desktop/Karchin Lab/data/IP22_processed.rds")

# getmode <- function(v) {
#    uniqv <- unique(v)
#    uniqv[which.max(tabulate(match(v, uniqv)))]
# }

set_k_choices <- writeSetKTable(all_set_results)
set_k_choices$chosen_K[6]= 2

best_set_chains <- collectBestKChains(all_set_results, chosen_K = set_k_choices$chosen_K)
chains <- mergeSetChains(best_set_chains, input_data)
plotChainsCCF(chains$w_chain)

sets_n <- writeClusterAssignmentsTables(chains$z_chain)
  mutate(Mut_ID = as.numeric(gsub("Mut","",Mut_ID)))%>%
  arrange(Mut_ID)
mut <- input_data$Mut_ID%>%
  cbind(sets)%>%
  rename("Mut" = ".")%>%
  filter(grepl('KRAS|GNAS',Mut, ignore.case = TRUE))
  
```


#tree
```{r}
w_mat <- estimateCCFs(chains$w_chain)
graph_G_pre <- prepareGraphForGabowMyers(w_mat, chains, input_data)
graph_G <- filterEdgesBasedOnCCFs(graph_G_pre, w_mat, thresh = 0.1)
enumerateSpanningTreesModified(graph_G, w_mat, sum_filter_thresh=0.5)
scores <- calcTreeScores(chains$w_chain, all_spanning_trees)
best_tree <- all_spanning_trees[[which.max(scores)]]
best_tree <- all_spanning_trees[[10]]
plotTree(best_tree)
plotEnsembleTree(all_spanning_trees)
subclone_props <- calcSubcloneProportions(w_mat, best_tree)
subclone_props[subclone_props<0]=0
subclone_props_n <- sapply(c(1,2,3), function(x) round(subclone_props[,x]/sum(subclone_props[,x]),digits = 5))
plotSubclonePie(subclone_props_n)
plotSubcloneBar(subclone_props_n)
```

# proportion bar plot
```{r}
subclone_props%>%
  as.data.frame()%>%
  mutate(clone = paste0("clone ",row.names(.)))%>%
  rename("Sample 1" = "V1","Sample 2" = "V2","Sample 3" = "V3")%>%
  gather(key = "sample", value = "porp", 1:3)%>%
  group_by(sample)%>%
  mutate(porp = ifelse(porp < 0, 0, porp),
         porp = porp/sum(porp))%>%
  ungroup()%>%
  ggplot(aes(x = sample, y = porp, fill = clone))+
  geom_bar(stat = "identity")
```

# create sample_pres for matrix calculation
```{r}
matchSamplePresence <- function(w_mat, chains, input_data) {
  map_z <- estimateClusterAssignments(chains$z_chain) 
  
  # pull one variant for each cluster
  single_var_clust <- map_z[match(unique(map_z$value), map_z$value), ] %>%
    mutate(mut_ind = as.numeric(gsub("z\\[|]", "", Parameter))) %>%
    arrange(value)
  
  samp_pres <- ifelse(input_data$y[single_var_clust$mut_ind, ] >=1, 1, 0)
  return(samp_pres)
}

estimateClusterAssignments <- function(z_chain) {
  it <- max(z_chain$Iteration)
  mcmc_z <- z_chain %>%
    group_by(Parameter, value) %>%
    summarize(n=n(),
              maxiter=it) %>%
    mutate(probability=n/maxiter)%>%
    ungroup()
  
  map_z <- mcmc_z %>%
    group_by(Parameter) %>%
    summarize(value=value[probability==max(probability)])
  
  # choose first cluster if equal probability
  map_z_count <- map_z %>% 
    group_by(Parameter) %>%
    summarize(map_count = n()) %>%
    ungroup()
  if (any(map_z_count$map_count > 1)) {
    mut_ind <- which(map_z_count$map_count > 1)
    for (i in mut_ind) {
      dup_var <- as.numeric(gsub("z\\[|]", "", map_z_count$Parameter[i]))
      map_z_dups <- which(gsub("z\\[|]", "", map_z$Parameter) == dup_var)
      dup_ind <- map_z_dups[-1]
      map_z <- map_z[-dup_ind, ]
    }
  }
  return(map_z)
}

samp_pres <- matchSamplePresence(w_mat, chains, input_data)
```


#my function to find trees (using matrix)
```{r}
#First filter connection by checking if going from more sample presence to less (graph_G_pre)
find_graph_G <- function(samp_pres,w_mat, thresh = 0.1){
  
  K <- nrow(w_mat)
  # check sample presence hierarchy
  x <- rowSums(samp_pres)
  # create constrain matrix (higher sample pres goes to lower pres, not the other way)
  xx <- x%*%t(x)
  constrainmatrix <- xx <= x^2
  # set diagnal to be false since cluster can't connect to itself
  diag(constrainmatrix) <- F
  # extra row to represent root
  constrainmatrix <- rbind(T, constrainmatrix)
  dimnames(constrainmatrix) <- list(c("root", 1:K), 1:K)
  constrainmatrix <- ifelse(constrainmatrix == T, 1,0)
  
  #then check if the parent and child (a connection) follows descendence rule (large to small)
  w_new <- rbind(1,w_mat)
  dd <- as.data.frame(which(constrainmatrix == T,arr.ind = T)) %>% 
    mutate(col = col+1,
           index = which(constrainmatrix == T))
  #child - parent
  change <- w_new[dd$col,]-w_new[dd$row,] > thresh
  #find which row has any(diff > thresh)
  cc <- rowSums(ifelse(change == T, 1,0))
  #update matrix
  constrainmatrix[dd$index[which(!cc == 0)]] = F
  return(constrainmatrix)
}

cmat <- find_graph_G(samp_pres,w_mat)
loc <- which(cmat == 1)
cmat[loc] = loc
cmat[-loc] = NA
test <- as.data.frame(cmat)

########################trying trees################

all_comb = combn(loc, ncol(cmat))
# sub_loc <- lapply(1:ncol(cmat), function(n) loc[loc < nrow(cmat)*(n) & loc >= nrow(cmat)*(n-1)+1])
# 
# trees <- crossing(sub_loc[[1]],sub_loc[[2]])
# n=2
# comb_tree <- function(sub_loc){
#   if (n == length(sub_loc)){
#     return(trees)
#   }else{
#     trees <- crossing(trees, sub_loc[[n+1]])
#     n = n+1
#     comb_tree(sub_loc)
#   }
# }
# 
# test <- comb_tree(sub_loc)

#job::job({all_comb <- permutations(n=length(loc), r = ncol(cmat), v = loc, repeats.allowed=F)})
trees <- as.data.frame(all_comb)
# find all trees
for (i in 1:ncol(cmat)){
  trees <- trees %>%
    rename("X" = colnames(trees)[i])%>%
    filter(X <= nrow(cmat)*i,
           X > nrow(cmat)*(i-1))
  colnames(trees) <- colnames(all_comb)
}
#check score
obtain_mat <- function(index, trees){
  temp <- matrix(0, nrow(cmat), ncol(cmat))
  temp[as.numeric(trees[index,])]=1
  return(temp)
}
# use to find the sum of all children is not too over the parents
calc_diff <- function(w_mat,index,mats, thresh = 0.2){
  w_new <- rbind(1,w_mat)
  mat <- mats[[index]]
  sum_child_diff <- mat%*%w_mat-w_new > thresh
  sum_child_diff <- ifelse(sum_child_diff == T, 1,0)
  if (sum(sum_child_diff) == 0){
    return(index)
  }
}
mats <- lapply(1:nrow(trees), function(row) obtain_mat(row, trees))
select_mat_index <- unlist(sapply(1:nrow(trees), function(row) calc_diff(w_mat, row, mats, thresh = 0.1)))
select_mat <- mats[select_mat_index]

topology_cost <- function(mat, w_mat){
  w_new <- rbind(1,w_mat)
  dd <- as.data.frame(which(mat == 1,arr.ind = T)) %>% 
    mutate(col = col+1)
  #child - parent
  change <- w_new[dd$col,]-w_new[dd$row,] > 0
  cc <- ifelse(change == T, 1, 0)
  t_score <- sum(cc)
  return(t_score)
}

mass_cost <- function(mat,w_mat){
  w_new <- rbind(1,w_mat)
  sum_child_diff <- mat%*%w_mat-w_new > 0
  sum_child_diff <- ifelse(sum_child_diff == T, 1,0)
  m_score <- sum(sum_child_diff)
  return(m_score)
}

score <- sapply(1:length(select_mat), 
                function(ind) topology_cost(select_mat[[ind]], w_mat)+mass_cost(select_mat[[ind]], w_mat))
our_tree <- select_mat[[which.min(score)]]
```