---
title: "single sample test"
author: "Lester"
date: "2023-01-24"
output: html_document
---

```{r}
library(pictograph)
library(tidyverse)
# library(rjags)
# setwd("~/GitHub/pictograph/les_test")
# source("../R/bic.R")
# source("../R/cluster_separately.R")
# source("../R/clustering_functions.R")
# source("../R/plot.R")
# source("../R/gabowmyers.R")
# source("../R/graph_ops.R")
# source("../R/metrics.R")
# source("../R/tree_scoring.R")
# source("../R/tree.R")
# source("../R/subclone-proportions.R")
#source("single_samp_func.R")
```

# prepare single sample data
```{r}
## change to input path
ori_data <- readRDS("C:/Users/Leste/OneDrive - Johns Hopkins/Desktop/Karchin Lab/data/pictograph-input/IP22_input_data.rds")

## split original data into single sample input
samp_comb <- combn(1:ori_data$S,1)
subset <- function(input_data, samp_comb, x){
  out <- list(y = input_data$y[,samp_comb[,x]],
              n = input_data$n[,samp_comb[,x]],
              tcn = input_data$tcn[,samp_comb[,x]],
              m = input_data$m[,samp_comb[,x]],
              I = input_data$I,
              S = 1,
              purity = input_data$purity[samp_comb[,x]],
              Sample_names = input_data$Sample_names[samp_comb[,x]],
              mutation_indices = seq_len(input_data$I),
              Mut_ID = input_data$Mut_ID)
}
subset_list <- lapply(1:ncol(samp_comb), function(x) subset(ori_data, samp_comb,x))

## pick one sample from list by changing the number in bracket
input_data <- subset_list[[4]]
```




# process the data
```{r pressure, echo=FALSE}
  all_set_results <- clusterSep(ori_data,
                              n.iter = 1000, n.burn = 100, thin = 1,
                              max_K = 5, one_box = TRUE, les_BIC = TRUE)

## plot ccf
chains <- all_set_results$best_chains
chains$w_chain%>%
  mutate(Cluster = gsub("w\\[(,*)\\]","\\1",Parameter))%>%
  ggplot(aes(x = Iteration, y = value))+
  geom_line() +
    theme_light() +
    facet_wrap("Cluster") +
    ylab("Cancer Cell Fraction")

## modify this function to plot BIC
plotBIC(all_set_results)
```

```{r}
sets <- writeClusterAssignmentsTable(chains$z_chain)%>%
  mutate(Mut_ID = as.numeric(gsub("Mut","",Mut_ID)))%>%
  arrange(Mut_ID)

ggplot(data = sets)+
  geom_point(aes(x = Cluster, y = Mut_ID))

mut <- input_data$Mut_ID%>%
  cbind(sets)%>%
  rename("Mut" = ".")%>%
  filter(grepl('KRAS|GNAS',Mut, ignore.case = TRUE))

```


```{r}
w_mat <- estimateCCFs(chains$w_chain)%>%
  cbind(matrix(rep(0, nrow(.)),nrow = nrow(.), ncol = 1))

# create all possible edges and then filter based on lineage precedence
graph_G <- expand.grid(parent = c(seq.int(1,nrow(w_mat),1),"root"),
                           child = c(seq.int(1,nrow(w_mat),1),"root"))%>%
  filter(parent != child,
         child != "root")%>%
  mutate(parent = ifelse(parent == "root", as.character(parent), as.numeric(parent)),
         child = as.numeric(child),
         edge = paste0(as.character(parent), "->", as.character(child)),
         parent.ccf = ifelse(parent == "root",1,w_mat[.$parent]),
         child.ccf = w_mat[.$child],
         topo_cost = child.ccf - parent.ccf)%>%
  filter(topo_cost < 0.1)%>%
  select(parent, child, edge)

enumerateSpanningTreesModified(graph_G, w_mat, sum_filter_thresh=0.5)
scores <- calcTreeScores(chains$w_chain, all_spanning_trees)

## no topology cost bc there was a filter before, all bad edges are removed
# get_score <- function(tree){
# top <- tree %>%
#   pull(topo_cost)%>%
#   sum()
# mas <- tree%>%
#   group_by(parent)%>%
#   mutate(sum_child = sum(child.ccf),
#          mass_cost = sum_child - parent.ccf)%>%
#   distinct(parent, .keep_all = TRUE)%>%
#   pull(mass_cost)%>%
#   sum()
# return(abs(top+mas))
# }
# scores <- sapply(all_spanning_trees, function(x) get_score(x))
best_tree <- all_spanning_trees[[which.max(scores)]]
plotTree(best_tree)
plotEnsembleTree(all_spanning_trees)
```

#plotBIC
```{r}
min <- all_set_results$best_K
elbow <- ifelse(is.logical(all_set_results$BIC), 1, findElbow2(all_set_results$BIC$BIC))
knee <- ifelse(is.logical(all_set_results$BIC), 1, findKnee(all_set_results$BIC$BIC))
bic_tb <- all_set_results$BIC
k_c <- bind_rows(bic_tb[min,],bic_tb[elbow,],bic_tb[knee,])%>%
  mutate(type = c("min","elbow","knee"))

# plot
bic_plot <- ggplot(bic_tb, aes(x = K_tested, y = BIC)) +
    theme_light() +
    geom_line() +
    geom_point(data = k_c, aes(color = type, size = type, shape = type), stroke = 1) +
    scale_shape_manual(values=c(19, 1, 1))+
    scale_color_manual(values=c('#999999',"#56B1F7", "#E69F00")) +
    scale_size_manual(values=c(1, 3, 5)) +
    #geom_point(data = elbow, color = , size = 4, shape = 1)
    theme(strip.background=element_blank(),
          strip.text = element_text(colour = 'black'),
          panel.grid.minor = element_blank()) +
    xlab("K")
```

#violin plot
```{r}
all_set_results <- readRDS("C:/Users/Leste/OneDrive - Johns Hopkins/Desktop/Karchin Lab/data/single_sample/ip22_1.rds")

vio <- all_set_results$best_chains$w_chain %>%
  mutate(cluster = gsub("w\\[(.*)\\]","\\1",Parameter))%>%
  ggplot(aes(cluster, value))+
  geom_violin(aes(fill=cluster),
                alpha=0.6,
                scale="width",
                draw_quantiles=c(0.25, 0.5, 0.75),
                color="white")+
  geom_violin(fill="transparent", color="black",
                scale="width", draw_quantiles=0.5) +
    theme_bw(base_size=12) +
    theme(strip.background=element_blank(),
          axis.text.x=element_text(size=12),
          panel.grid=element_blank(),
          legend.pos="bottom") +
    ylab("Posterior CCF") + xlab("") +ylim(c(0, 1)) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
  
```


```{r}
all_set_results <- readRDS("C:/Users/Leste/OneDrive - Johns Hopkins/Desktop/Karchin Lab/data/single_sample/ip22_1.rds")

ca<- all_set_results$best_chains$z_chain%>%
  group_by(Parameter, value)%>%
  summarise(prob = n()/1000)%>%
  ungroup()%>%
  group_by(Parameter)%>%
  filter(prob == max(prob))%>%
  ungroup()%>%
  arrange(desc(value))%>%
  mutate(Mut_ID = gsub("z\\[(.*)\\]","\\1",Parameter))

ca$Mut_ID <- factor(ca$Mut_ID, levels=c(ca$Mut_ID))

ggplot(ca, aes(x = value, y = Mut_ID, color = prob)) +
    theme_light() +
    scale_y_discrete(drop = T, name = "Variant") +
    scale_x_continuous(breaks = 1:K, name = "Cluster", labels = 1:K) +
    geom_point() +
    theme(panel.grid.minor = element_blank(),
          strip.background=element_blank(),
          strip.text = element_text(colour = 'black'),
          strip.text.y = element_text(angle = 0)) +
    scale_color_gradient(limits = c(0,1))
```