---
title: "Untitled"
author: "Lester"
date: "2022-11-28"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
devtools::load_all("~/GitHub/pictograph")
```

## Get the cluster info
```{r pressure, echo=FALSE}
# all_set_results <- clusterSep(input_data,
#                               n.iter = 1000, n.burn = 100, thin = 1,
#                               max_K = 5)
input_data <- readRDS("C:/Users/Leste/Desktop/Karchin Lab/data/pictograph-input/IP22_input_data.rds")
all_set_results <- readRDS("C:/Users/Leste/Desktop/Karchin Lab/data/IP22_processed.rds")
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}


set_k_choices <- writeSetKTable(all_set_results)

best_set_chains <- collectBestKChains(all_set_results, chosen_K = set_k_choices$chosen_K)
chains <- mergeSetChains(best_set_chains, input_data)
#plotChainsCCF(chains$w_chain)

sets <- writeClusterAssignmentsTable(chains$z_chain)%>%
  mutate(Mut_ID = as.numeric(gsub("Mut","",Mut_ID)))%>%
  arrange(Mut_ID)
```

## seperating to subsets
```{r}
samp_comb <- combn(1:input_data$S,2)
subset <- function(input_data, samp_comb, x){
  out <- list(y = input_data$y[,samp_comb[,x]],
              n = input_data$n[,samp_comb[,x]],
              tcn = input_data$tcn[,samp_comb[,x]],
              m = input_data$m[,samp_comb[,x]],
              I = input_data$I,
              S = length(samp_comb[,x]),
              purity = input_data$purity[samp_comb[,x]],
              Sample_names = input_data$Sample_names[samp_comb[,x]],
              Mut_ID = input_data$Mut_ID)
}
subset_list <- lapply(1:ncol(samp_comb), function(x) subset(input_data, samp_comb,x))
```

## run mcmc for subset
```{r}
mcmc <- function(data,jags.file,
                 n.iter = 10000, n.burn = 1000, thin = 10,n.chains=1,n.adapt=1000,
                 mc.cores = 1,params = c("w", "ystar"),beta.prior = FALSE,
                 inits = list(".RNG.name" = "base::Wichmann-Hill",".RNG.seed" = 123)){
  
  jags.m <- jags.model(jags.file,
                         data,
                         n.chains = n.chains,
                         inits = inits,
                         n.adapt = n.adapt)
    if (n.burn > 0) update(jags.m, n.burn)
    samps <- coda.samples(jags.m, params, n.iter=n.iter, thin=thin)
    
    return(samps)
}

temp <- input_data$y %>%
  as.data.frame()%>%
  mutate_if(is.numeric, ~1 * (. != 0))%>%
  unite("type", colnames(.), remove = FALSE)%>%
  mutate(num = as.numeric(rownames(.)),
         type = gsub("_","",type))
boxes <- lapply(unique(temp$type), function(x) filter(temp, type == x)$num)
out <- list()
extdir <- system.file("extdata", package="pictograph")
jags.file.test <- file.path(extdir, "sub_test.jags")


for (i in 1:length(boxes)){
  type <- unique(temp$type)[i]
  K <- filter(set_k_choices, set_name_bin==type)$chosen_K
  z <- sets[boxes[[i]],]$Cluster - min(sets[boxes[[i]],]$Cluster)+1
  box <- list(y = subset_list[[1]]$y[boxes[[i]],],
              n = subset_list[[1]]$n[boxes[[i]],],
              tcn = subset_list[[1]]$tcn[boxes[[i]],],
              m = subset_list[[1]]$m[boxes[[i]],],
              I = length(boxes[[i]]),
              S = subset_list[[1]]$S,
              purity = subset_list[[1]]$purity,
              #Sample_names = subset_list[[1]]$Sample_names,
              #Mut_ID = subset_list[[1]]$Mut_ID[boxes[[i]]],
              z = z,
              K = K)
  if (box$I > 1) {
    if (sum(box$y) == 0){
      sample_to_sort <- 1
    }else{
      sample_to_sort <- which(colSums(box$y) > 0)[1]
    }
     
  } else {
    if (sum(box$y) == 0){
      sample_to_sort <- 1
    }else{
      sample_to_sort <- which(box$y > 0)[1]
    }
    
  }
  box$sample_to_sort <- sample_to_sort
  
  # run mcmc chain
  out_chain <- mcmc(box,jags.file.test)[[1]]
  
  # convert to original clustering number
  col <- colnames(out_chain)[grep("w",colnames(out_chain))]%>%
    as.data.frame()%>%
    rename("w_para" = ".")%>%
    mutate(old_z = gsub("w\\[(.*),.*","\\1",w_para),
           other = gsub("w\\[(.*)(,.*)","\\2",w_para),
           z = as.numeric(old_z) + min(sets[boxes[[i]],]$Cluster)-1,
           new_w = paste0("w[",z,other))
  colnames(out_chain)[grep("w",colnames(out_chain))] <- col$new_w 
  
  # convert w chain to data frame to build w matrix
  out_w <- out_chain[,grep("w",colnames(out_chain))]%>%
    as.data.frame()%>%
    gather(key = "Parameter",value = "value")
  out[[type]] <- out_w
}
w_chain <- do.call(rbind.data.frame, out)%>%
  mutate()
w_mat <- estimateCCFs(w_chain)
samp_pres <- temp %>%
  rename("Mut_ID" = "num")%>%
  left_join(sets)%>%
  distinct(Cluster, .keep_all = TRUE)%>%
  select(subset_list[[1]]$Sample_names)
```
# ordering boxes
```{r}
w_mat <- as.data.frame(w_mat)%>%mutate(Cluster = as.numeric(rownames(.)))
w_box <- temp %>%
  rename("Mut_ID" = "num")%>%
  left_join(sets)
  distinct(Cluster, .keep_all = TRUE)%>%
  select(type,Cluster)%>%
  left_join(w_mat)
  
  
```


# find trees (using matrix)
```{r}
#First filter connection by checking if going from more sample presence to less (graph_G_pre)
find_graph_G <- function(samp_pres,w_mat, thresh = 0.1){
  K <- nrow(w_mat)
  x <- rowSums(samp_pres)
  xx <- x%*%t(x)
  #consider change T/F to 1/0 for future calculation
  constrainmatrix <- xx <= x^2
  diag(constrainmatrix) <- F
  constrainmatrix <- rbind(T, constrainmatrix)
  dimnames(constrainmatrix) <- list(c("root", 1:K), 1:K)
  constrainmatrix <- ifelse(constrainmatrix == T, 1,0)
  
  #then check if the parent and child (a connection) follows descendence rule (large to small)
  w_new <- rbind(1,w_mat)
  dd <- as.data.frame(which(constrainmatrix == T,arr.ind = T)) %>% 
    mutate(col = col+1,
           index = which(constrainmatrix == T))
  #child - parent
  change <- w_new[dd$col,]-w_new[dd$row,] > thresh
  change_p <- w_new[dd$row,] - w_new[dd$col,] 
  #find which row has any(diff > thresh)
  cc <- rowSums(ifelse(change == T, 1,0))
  #update matrix
  constrainmatrix[dd$index[which(!cc == 0)]] = F
  return(constrainmatrix)
}

cmat <- find_graph_G(samp_pres,w_mat)
loc <- which(cmat == 1)
cmat[loc] = loc
cmat[-loc] = NA
# test <- as.data.frame(cmat)
# aa <- unique(test[,c('1','2')])

########################trying trees################

#all_comb <- combn(loc, 10)
sub_loc <- lapply(1:ncol(cmat), function(n) loc[loc < nrow(cmat)*(n) & loc >= nrow(cmat)*(n-1)+1])

trees <- crossing(sub_loc[[1]],sub_loc[[2]])
n=2
comb_tree <- function(sub_loc){
  if (n == length(sub_loc)){
    return(trees)
  }else{
    trees <- crossing(trees, sub_loc[[n+1]])
    n = n+1
    comb_tree(sub_loc)
  }
}

test <- comb_tree(sub_loc)

#job::job({all_comb <- permutations(n=length(loc), r = ncol(cmat), v = loc, repeats.allowed=F)})
trees <- as.data.frame(all_comb)
# find all trees
for (i in 1:ncol(cmat)){
  trees <- trees %>%
    rename("X" = colnames(trees)[i])%>%
    filter(X <= nrow(cmat)*i,
           X > nrow(cmat)*(i-1))
  colnames(trees) <- colnames(all_comb)
}
#check score
obtain_mat <- function(index, trees){
  temp <- matrix(0, nrow(cmat), ncol(cmat))
  temp[as.numeric(trees[index,])]=1
  return(temp)
}
# use to find the sum of all children is not too over the parents
calc_diff <- function(w_mat,index,mats, thresh = 0.2){
  w_new <- rbind(1,w_mat)
  mat <- mats[[index]]
  sum_child_diff <- mat%*%w_mat-w_new > thresh
  sum_child_diff <- ifelse(sum_child_diff == T, 1,0)
  if (sum(sum_child_diff) == 0){
    return(index)
  }
}
mats <- lapply(1:nrow(trees), function(row) obtain_mat(row, trees))
select_mat_index <- unlist(sapply(1:nrow(trees), function(row) calc_diff(w_mat, row, mats, thresh = 0.1)))
select_mat <- mats[select_mat_index]

topology_cost <- function(mat, w_mat){
  w_new <- rbind(1,w_mat)
  dd <- as.data.frame(which(mat == 1,arr.ind = T)) %>% 
    mutate(col = col+1)
  #child - parent
  change <- w_new[dd$col,]-w_new[dd$row,] > 0
  cc <- ifelse(change == T, 1, 0)
  t_score <- sum(cc)
  return(t_score)
}

mass_cost <- function(mat,w_mat){
  w_new <- rbind(1,w_mat)
  sum_child_diff <- mat%*%w_mat-w_new > 0
  sum_child_diff <- ifelse(sum_child_diff == T, 1,0)
  m_score <- sum(sum_child_diff)
  return(m_score)
}

score <- sapply(1:length(select_mat), 
                function(ind) topology_cost(select_mat[[ind]], w_mat)+mass_cost(select_mat[[ind]], w_mat))
our_tree <- select_mat[[which.min(score)]]
```