---
title: "Untitled"
author: "Lester"
date: "2022-10-02"
output: html_document
---

```{r setup, include=FALSE}
#library(pictograph)
library(dplyr)
library(tidyr)
devtools::load_all("~/GitHub/pictograph")
```


```{r cars}
#input_data<- readRDS("C:/Users/Leste/Desktop/Karchin Lab/data/pictograph-input/IP29_input_data.rds")
input_data <- readRDS("C:/Users/Leste/Desktop/Karchin Lab/data/pictograph-input/IP04_input_data.rds")

# data("toy2")
# set.seed(42)
# input <- MDA231
# pur <- runif(ncol(input$R), min=0.5, max=0.9)
# pur_mat <- matrix(pur,nrow = nrow(input$R), ncol = ncol(input$R), byrow = TRUE)
# vaf <- input$R/input$X
# mul <- vaf/pur_mat*(pur_mat*input$WM+2*(1-pur_mat))
# m <- apply(mul, MARGIN = 2, function(x) ifelse(x<1, 1,round(x)))
# canopy_data <- list(y = input$R,
#                     n = input$X,
#                     tcn = round(input$WM),
#                     I = nrow(input$R),
#                     S = ncol(input$R),
#                     purity = pur,
#                     m = m)
# data("sim_data_1")
# input_data <- list(y = sim_data_1$y,
#                    n = sim_data_1$n,
#                    purity = sim_data_1$purity,
#                    tcn = sim_data_1$tcn,
#                    m = sim_data_1$m,
#                    I = sim_data_1$I,
#                    S = sim_data_1$S)
```

# ip04

## Get the cluster info
```{r pressure, echo=FALSE}
all_set_results <- clusterSep(input_data,
                              n.iter = 1000, n.burn = 100, thin = 1,
                              max_K = 5)
#all_set_results <- readRDS("C:/Users/Leste/Desktop/Karchin Lab/data/IP23_processed.rds")

# jobarg = list(
#   import = c("subset_list"),
#   packages = c("dplyr","tidyr","stringr","rjags"),
#   opts = list(mc.cores = 2)
# )
# 
# job_code = quote({
#   all_set_results1 <- clusterSep(subset_list[[1]],
#                               n.iter = 1000, n.burn = 100, thin = 1,
#                               max_K = 5)
# })
# job::job({
#   library(dplyr)
#   library(tidyr)
#   library(stringr)
#   devtools::load_all("~/GitHub/pictograph")
#   all_set_results5 <- clusterSep(subset_list[[5]],
#                               n.iter = 1000, n.burn = 100, thin = 1,
#                               max_K = 5)}, packages = NULL)



# all_set_results <- all_set_results5
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}


set_k_choices <- writeSetKTable(all_set_results)
set_k_choices$chosen_K[1] = 2

# plotBIC(all_set_results)
## be careful, when choosing high k, samp_pres rows doesn't match w_mat rows
# set_k_choices$chosen_K[3] = 2
# set_k_choices$chosen_K[10] = 3
best_set_chains <- collectBestKChains(all_set_results, chosen_K = set_k_choices$chosen_K)
chains <- mergeSetChains(best_set_chains, input_data)
plotChainsCCF(chains$w_chain)
# plotCCFViolin(chains$w_chain, chains$z_chain, indata = IP14)
# a <- plotClusterAssignmentProbVertical(chains$z_chain, chains$w_chain)
# writeClusterCCFsTable(chains$w_chain)
# b <- writeClusterAssignmentsTable(chains$z_chain)

sets <- writeClusterAssignmentsTable(chains$z_chain)%>%
  mutate(Mut_ID = gsub("Mut","",Mut_ID))
```

## seperating to subsets
```{r}
samp_comb <- combn(1:input_data$S,2)
subset <- function(input_data, samp_comb, x){
  out <- list(y = input_data$y[,samp_comb[,x]],
              n = input_data$n[,samp_comb[,x]],
              tcn = input_data$tcn[,samp_comb[,x]],
              m = input_data$m[,samp_comb[,x]],
              I = input_data$I,
              S = length(samp_comb[,x]),
              purity = input_data$purity[samp_comb[,x]],
              Sample_names = input_data$Sample_names[samp_comb[,x]],
              Mut_ID = input_data$Mut_ID)
}
subset_list <- lapply(1:ncol(samp_comb), function(x) subset(input_data, samp_comb,x))
```


## cluster subset based on earlier cluster assignment
```{r}
test <- input_data

m = test$m
  # mutate(Mut_ID = rownames(.)) %>%
  # left_join(sets)%>%
  # group_by(Cluster)%>%
  # summarise(across(where(is.numeric), sum))%>%
  # select(-Cluster)%>%
  # as.matrix()

p = diag(test$purity,length(test$purity),length(test$purity))

pdot = test$purity

c = test$tcn
  # mutate(Mut_ID = rownames(.)) %>%
  # left_join(sets)%>%
  # group_by(Cluster)%>%
  # summarise(across(where(is.numeric), sum))%>%
  # select(-Cluster)%>%
  # as.matrix()

y = test$y
  # mutate(Mut_ID = rownames(.)) %>%
  # left_join(sets)%>%
  # group_by(Cluster)%>%
  # summarise(across(where(is.numeric), sum))%>%
  # select(-Cluster)%>%
  # as.matrix()

n = test$n
  # mutate(Mut_ID = rownames(.)) %>%
  # left_join(sets)%>%
  # group_by(Cluster)%>%
  # summarise(across(where(is.numeric), sum))%>%
  # select(-Cluster)%>%
  # as.matrix()

v = y/n

  
CCF <- as.data.frame(v*sweep(c%*%p, 2, -2*(1-pdot))/(m%*%p))%>%
  mutate(Mut_ID = rownames(.))%>%
  left_join(sets)%>%
  group_by(Cluster)%>%
  summarise(across(where(is.numeric), mean))%>%
  ungroup()

```

tree
```{r}
w_mat <- estimateCCFs(chains$w_chain)
graph_G_pre <- prepareGraphForGabowMyers(w_mat, chains, input_data)
graph_G <- filterEdgesBasedOnCCFs(graph_G_pre, w_mat, thresh = 0.1)
enumerateSpanningTreesModified(graph_G, w_mat, sum_filter_thresh=0.1)
scores <- calcTreeScores(chains$w_chain, all_spanning_trees)
best_tree <- all_spanning_trees[[which.max(scores)]]
plotTree(best_tree)
plotEnsembleTree(all_spanning_trees)
subclone_props <- calcSubcloneProportions(w_mat, best_tree)
#subclone_props_n <- sapply(c(1,2), function(x) subclone_props[,x]/sum(subclone_props[,x]))
plotSubclonePie(subclone_props_n)
```

#matchSamplePresence in graphop.R
```{r}
matchSamplePresence <- function(w_mat, chains, input_data) {
  map_z <- estimateClusterAssignments(chains$z_chain) 
  
  # pull one variant for each cluster
  single_var_clust <- map_z[match(unique(map_z$value), map_z$value), ] %>%
    mutate(mut_ind = as.numeric(gsub("z\\[|]", "", Parameter))) %>%
    arrange(value)
  
  samp_pres <- ifelse(input_data$y[single_var_clust$mut_ind, ] >=1, 1, 0)
  return(samp_pres)
}

estimateClusterAssignments <- function(z_chain) {
  it <- max(z_chain$Iteration)
  mcmc_z <- z_chain %>%
    group_by(Parameter, value) %>%
    summarize(n=n(),
              maxiter=it) %>%
    mutate(probability=n/maxiter)%>%
    ungroup()
  
  map_z <- mcmc_z %>%
    group_by(Parameter) %>%
    summarize(value=value[probability==max(probability)])
  
  # choose first cluster if equal probability
  map_z_count <- map_z %>% 
    group_by(Parameter) %>%
    summarize(map_count = n()) %>%
    ungroup()
  if (any(map_z_count$map_count > 1)) {
    mut_ind <- which(map_z_count$map_count > 1)
    for (i in mut_ind) {
      dup_var <- as.numeric(gsub("z\\[|]", "", map_z_count$Parameter[i]))
      map_z_dups <- which(gsub("z\\[|]", "", map_z$Parameter) == dup_var)
      dup_ind <- map_z_dups[-1]
      map_z <- map_z[-dup_ind, ]
    }
  }
  return(map_z)
}

## why only choose one from each cluster? sampling check? why we need this step
samp_pres <- matchSamplePresence(w_mat, chains, subset_list[[1]])
```


#my function to find trees (using matrix)
```{r}
#First filter connection by checking if going from more sample presence to less (graph_G_pre)
find_graph_G <- function(samp_pres,w_mat, thresh = 0.1){
  K <- nrow(w_mat)
  x <- rowSums(samp_pres)
  xx <- x%*%t(x)
  #consider change T/F to 1/0 for future calculation
  constrainmatrix <- xx <= x^2
  diag(constrainmatrix) <- F
  constrainmatrix <- rbind(T, constrainmatrix)
  dimnames(constrainmatrix) <- list(c("root", 1:K), 1:K)
  constrainmatrix <- ifelse(constrainmatrix == T, 1,0)
  
  #then check if the parent and child (a connection) follows descendence rule (large to small)
  w_new <- rbind(1,w_mat)
  dd <- as.data.frame(which(constrainmatrix == T,arr.ind = T)) %>% 
    mutate(col = col+1,
           index = which(constrainmatrix == T))
  #child - parent
  change <- w_new[dd$col,]-w_new[dd$row,] > thresh
  #find which row has any(diff > thresh)
  cc <- rowSums(ifelse(change == T, 1,0))
  #update matrix
  constrainmatrix[dd$index[which(!cc == 0)]] = F
  return(constrainmatrix)
}

cmat <- find_graph_G(samp_pres,w_mat)
loc <- which(cmat == 1)
cmat[loc] = loc
cmat[-loc] = NA
test <- as.data.frame(cmat)
aa <- unique(test[,c('1','2')])

########################trying trees################

all_comb = combn(loc, ncol(cmat))
# sub_loc <- lapply(1:ncol(cmat), function(n) loc[loc < nrow(cmat)*(n) & loc >= nrow(cmat)*(n-1)+1])
# 
# trees <- crossing(sub_loc[[1]],sub_loc[[2]])
# n=2
# comb_tree <- function(sub_loc){
#   if (n == length(sub_loc)){
#     return(trees)
#   }else{
#     trees <- crossing(trees, sub_loc[[n+1]])
#     n = n+1
#     comb_tree(sub_loc)
#   }
# }
# 
# test <- comb_tree(sub_loc)

#job::job({all_comb <- permutations(n=length(loc), r = ncol(cmat), v = loc, repeats.allowed=F)})
trees <- as.data.frame(all_comb)
# find all trees
for (i in 1:ncol(cmat)){
  trees <- trees %>%
    rename("X" = colnames(trees)[i])%>%
    filter(X <= nrow(cmat)*i,
           X > nrow(cmat)*(i-1))
  colnames(trees) <- colnames(all_comb)
}
#check score
obtain_mat <- function(index, trees){
  temp <- matrix(0, nrow(cmat), ncol(cmat))
  temp[as.numeric(trees[index,])]=1
  return(temp)
}
# use to find the sum of all children is not too over the parents
calc_diff <- function(w_mat,index,mats, thresh = 0.2){
  w_new <- rbind(1,w_mat)
  mat <- mats[[index]]
  sum_child_diff <- mat%*%w_mat-w_new > thresh
  sum_child_diff <- ifelse(sum_child_diff == T, 1,0)
  if (sum(sum_child_diff) == 0){
    return(index)
  }
}
mats <- lapply(1:nrow(trees), function(row) obtain_mat(row, trees))
select_mat_index <- unlist(sapply(1:nrow(trees), function(row) calc_diff(w_mat, row, mats, thresh = 0.1)))
select_mat <- mats[select_mat_index]

topology_cost <- function(mat, w_mat){
  w_new <- rbind(1,w_mat)
  dd <- as.data.frame(which(mat == 1,arr.ind = T)) %>% 
    mutate(col = col+1)
  #child - parent
  change <- w_new[dd$col,]-w_new[dd$row,] > 0
  cc <- ifelse(change == T, 1, 0)
  t_score <- sum(cc)
  return(t_score)
}

mass_cost <- function(mat,w_mat){
  w_new <- rbind(1,w_mat)
  sum_child_diff <- mat%*%w_mat-w_new > 0
  sum_child_diff <- ifelse(sum_child_diff == T, 1,0)
  m_score <- sum(sum_child_diff)
  return(m_score)
}

score <- sapply(1:length(select_mat), 
                function(ind) topology_cost(select_mat[[ind]], w_mat)+mass_cost(select_mat[[ind]], w_mat))
our_tree <- select_mat[[which.min(score)]]
```

#find subclone proportion
```{r}
runMCMCForABox <- function(box, 
                           n.iter = 10000, n.burn = 1000, thin = 10, mc.cores = 1,
                           inits = list(".RNG.name" = "base::Wichmann-Hill",
                                        ".RNG.seed" = 123),
                           params = c("z", "w", "ystar"),
                           max_K = 5, model_type = "simple",
                           beta.prior = FALSE) {
  # returns samps_list 
  box_input_data <- getBoxInputData(box)
  
  extdir <- system.file("extdata", package="pictograph")
  if (box$I == 1) {
    jags.file.K1 <- file.path(extdir, "spike_and_slab_purity_2_K1_I1.jags")
    box_input_data$I <- NULL
  } else {
    jags.file.K1 <- file.path(extdir, "spike_and_slab_purity_2_K1.jags")
  }
  
  if (model_type == "simple") {
    jags.file <- file.path(extdir, "model-test.jags") # fixes order of CCFs in one sample, not spike and slab 
  } else if (model_type == "spike_and_slab") {
    jags.file <- file.path(extdir, "spike_and_slab_purity_ident.jags") # fixing order of CCFs in one sample
  } else stop("provide model_type either 'spike_and_slab' or 'simple'")
  
  # choose sample in which mutations are present
  if (box$I > 1) {
    if (sum(box$y) == 0){
      sample_to_sort <- 1
    }else{
      sample_to_sort <- which(colSums(box$y) > 0)[1]
    }
     
  } else {
    if (sum(box$y) == 0){
      sample_to_sort <- 1
    }else{
      sample_to_sort <- which(box$y > 0)[1]
    }
    
  }
  
  
  samps_K1 <- runMCMC(box_input_data, 1, jags.file.K1, 
                      inits, params, n.iter=n.iter, thin=thin, n.burn=n.burn)
  if(box$I == 1) {
    colnames(samps_K1[[1]])[which(colnames(samps_K1[[1]]) == "z")] <- "z[1]"
  }
  
  # Max number of clusters cannot be more than number of mutations
  max_K <- min(max_K, length(box$mutation_indices)) 
  if (max_K > 1) {
  
    box_input_data$sample_to_sort <- sample_to_sort
    
    samps_2 <- parallel::mclapply(2:max_K,
                                  function(k) runMCMC(box_input_data, k,
                                                      jags.file, inits, params,
                                                      n.iter=n.iter, thin=thin,
                                                      n.burn=n.burn,
                                                      beta.prior=beta.prior),
                                  mc.cores=mc.cores)
    
    samps_list <- c(list(samps_K1), samps_2)
    names(samps_list) <- paste0("K", 1:max_K)
    return(samps_list)
    
  } else {
    names(samps_K1) <- "K1"
    return(samps_K1)
  }
  
}


estimateCCFs <- function(w_chain) {
  S <- numberSamples(w_chain)
  K <- numberClusters(w_chain)
  # density plot
  w.dens <- ggplot(w_chain, aes(x = value)) +
    geom_density() +
    facet_wrap(~Parameter, ncol = S, scales = "free_y") +
    theme_light()
  # find peak for MAP w
  w.dens.p <- ggplot_build(w.dens)$data[[1]]
  w.map <- w.dens.p %>%
    as_tibble() %>%
    group_by(PANEL) %>%
    arrange(y)%>%
    slice(1)%>%
    ## need ungroup()
    ungroup()%>%
    mutate(Parameter = unique(w_chain$Parameter),
           value_rounded = round(x, 2))%>%
    select(PANEL, x,Parameter, value_rounded)
  ########there is no max when everythign is zero############
  #   summarize(value = x[max(y) == y])
  # w.map <- w.map %>%
  #   mutate(Parameter = unique(w_chain$Parameter),
  #          value_rounded = round(value, 2))
  # return w matrix
  w.map.matrix <- matrix(w.map$value_rounded, K, S, byrow=TRUE)
  return(w.map.matrix)
}
```