---
title: "Untitled"
author: "Lester"
date: "2023-03-03"
output: html_document
---

```{r setup, include=FALSE}
library(UpSetR)
library(tidyverse)
library(readxl)
```

## Load data from excel
```{r cars}
#gather file path
files <- list.files("C:/Users/Leste/Karchin Lab Dropbox/YunZhou Liu/PanIN-2023/PICTograph Mutation Calls 1.31.23/", full.names = T)

#read in files
file_list <- lapply(files, function(x) read_excel(x)%>%
                      select(contains(c("Hugo_Symbol","HGVSp_Short")), Tumor_Seq_Allele2)%>%
                      mutate(file = gsub(".*31.23/(.*) Filter.*","\\1",x)))


#
## excels has duplicated columns, and for AB_14_1.3&1.4 two columns of HGVSp is not the same
## duplicated() remove most of them, select(c(1:2)) resolve issue above, first one always more info
ff <- lapply(1:length(file_list), function(x) file_list[[x]][!duplicated(as.list(file_list[[x]]))]%>%
                      select(c(1:2,"file","Tumor_Seq_Allele2"))%>%
                      rename("Hugo_Symbol" = grep("Hugo",colnames(.)),
                             "HGVSp_Short" = grep("HGVS", colnames(.)),
                             "ALT" = "Tumor_Seq_Allele2"))%>%
  do.call(rbind,.)%>%
  mutate(gene = paste0(Hugo_Symbol,HGVSp_Short),
         region = gsub("(.*)\\..*","\\1",file),
         region = gsub(" ","_",region))%>%
  #one file has duplicaated gene name, removed here
  group_by(file)%>%
  distinct(gene, .keep_all = T)%>%
  ungroup()%>%
  select(gene, file, region, ALT)

region <- unique(ff$region)
# remove TC98_2 bc 98_2.5 has duplicated gene name
#reigon <- reigon[-12]
new_rei <- c("TC_92","AB_14","AB_17")

# this function still consider each panin reigono seperately
get_list <- function(rei, dat){
  #in tc92_1, 2 KRAS_Q61H have different mutations
  mut<- dat%>%
    filter(grepl(rei,.$region))%>%
    mutate(type = paste0(gene, ALT))%>%
    spread(key = file, value = gene)
  
  order = colnames(mut[,-c(1,2,3)])
  
  temp <- mut[,-c(1,2,3)]%>%
    mutate_all(function(x) ifelse(is.na(x),0,1))%>%
    unite("presence", colnames(.),sep = "", remove = F)
  summ <- lapply(unique(temp$presence), function(x) mut$type[temp$presence==x])
  names(summ) = unique(temp$presence)
  
  mut_ <- as.list(mut[,-c(1,2,3)])
  
  for (i in 1:length(mut_)){
    mut_[[i]] <- mut_[[i]][!is.na(mut_[[i]])]
  }
  
     
  out <- list(mut = mut_, presence = summ, order = order)
  return(out)
}


dat_in <- lapply(reigon, function(x) get_list(x,ff))
```

# new xl
```{r}
sheets <- c("92",'114','117')
cp <- "C:/Users/Leste/Downloads/Supplementary Table 5 WES Data New add CN.xlsx"
xl <- lapply(sheets, function(x) read_excel(cp,skip = 2, col_names = T, sheet = x)%>%
                    mutate(file = x))%>%
  do.call(rbind,.)%>%
  select(`Gene Name`,Chromosome, `Start position`,`Protein Change`,Depth, 
         `Alternate Count`,`cDNA Change`, `Sample ID`,Region,Lesion,`Patient ID`)%>%
  dplyr::rename("Hugo_Symbol" = "Gene Name", "Start_Position" = "Start position", "y" = "Alternate Count", 
         "n" = "Depth", "HGVSp" = "Protein Change","DNAc" = "cDNA Change")%>%
  mutate(ref = gsub(".*(\\w)>(\\w)", "\\1", DNAc),
         alt = gsub(".*(\\w)>(\\w)", "\\2", DNAc),
         Chromosome = paste0("chr",Chromosome),
         gene = paste0(Hugo_Symbol, HGVSp),
         type = paste0(`Patient ID`, Lesion, Region))%>%
  filter(!grepl("PDAC", `Sample ID`),
#######removed deletion, can't find the ref and alt############
         !grepl("del",DNAc))
c92 <- xl %>%
  filter(`Patient ID` == "92")%>%
    mutate(Lesion = ifelse(Lesion == "A", 1,
                    ifelse(Lesion == "B", 4,
                    ifelse(grepl("D",Lesion), 6, Lesion))))%>%
  # didn't find lesion C in the processed cns file
  filter(!Lesion == 'C')
c14 <- xl %>%
  filter(`Patient ID` == "114")%>%
    mutate(Lesion = ifelse(Lesion == "A", 1,
                    ifelse(Lesion == "B", 2,Lesion)),
           `Patient ID` = "14")
c17 <- xl %>%
  filter(`Patient ID` == "117")%>%
    mutate(Lesion = ifelse(Lesion == "A", 1,Lesion),
           `Patient ID` = "17")

newxl <- rbind(c92,c14,c17)%>%
  mutate(Lesion = ifelse(grepl("H", `Sample ID`), paste0(Lesion,"H"), Lesion),
         Lesion = ifelse(grepl("L", `Sample ID`), paste0(Lesion,"L"), Lesion),
         file = paste0(`Patient ID`,Lesion,Region),
         region = paste0(`Patient ID`,Lesion),
         ALT = alt,
         region = gsub("[A-Z]","",region))%>%
  select(gene, file, region,ALT)
  

# remove TC98_2 bc 98_2.5 has duplicated gene name
#reigon <- reigon[-12]
get_list <- function(rei, dat){
  #in tc92_1, 2 KRAS_Q61H have different mutations
  mut<- dat%>%
    filter(grepl(rei,.$region))%>%
    mutate(type = paste0(gene, ALT))%>%
    spread(key = file, value = gene)
  
  order = colnames(mut[,-c(1,2,3)])
  
  temp <- mut[,-c(1,2,3)]%>%
    mutate_all(function(x) ifelse(is.na(x),0,1))%>%
    unite("presence", colnames(.),sep = "", remove = F)
  summ <- lapply(unique(temp$presence), function(x) mut$type[temp$presence==x])
  names(summ) = unique(temp$presence)
  
  mut_ <- as.list(mut[,-c(1,2,3)])
  
  for (i in 1:length(mut_)){
    mut_[[i]] <- mut_[[i]][!is.na(mut_[[i]])]
  }
  
     
  out <- list(mut = mut_, presence = summ, order = order)
  return(out)
}

regions <- unique(newxl$region)
dat_in <- lapply(regions, function(x) get_list(x,newxl))
names(dat_in) <- regions
```



## load from rds (not updated)
```{r}
# files <- list.files("C:/Users/Leste/Karchin Lab Dropbox/YunZhou Liu/for-lester (1)/pictograph-input-PanIN-AB", full.names = T)
# 
# reigon <- list.files("C:/Users/Leste/Karchin Lab Dropbox/YunZhou Liu/for-lester (1)/pictograph-input-PanIN-AB")
# 
# file_list <- lapply(files, function(x) list(y = readRDS(x)[[2]],
#                                             mut_id = readRDS(x)[[1]]))
# get_list <- function(a_list){
#   mut <- a_list[[2]]
#   y <- a_list[[1]]%>%
#     as.data.frame()%>%
#     mutate_all(function(x) ifelse(x == 0,NA,mut))%>%
#     as.list()
#   summary <- a_list[[1]]%>%
#     as.data.frame()%>%
#     mutate_all(function(x) ifelse(x != 0,"1","0"))%>%
#     unite("type", colnames(.),sep = "", remove = F)
#   summ <- lapply(unique(summary$type), function(x) as.data.frame(mut[summary$type==x]))
#   names(summ) = unique(summary$type)
#   for (i in 1:length(y)){
#     y[[i]] <- y[[i]][!is.na(y[[i]])]
#   }
#   
#   out <- list(y = y, mut = summ)
#   return(out)
# }
# 
# dat_in <- lapply(file_list, function(x) get_list(x))
# names(dat_in) <- gsub("panin_number_(.*)_picto.*","\\1",reigon)
```

## from tsv
```{r}
files <- list.files("C:/Users/Leste/Desktop/summary/", pattern = "S\\d\\d_\\d+.csv",full.names = T)
xl <- lapply(files, function(x) read.csv(x)%>%
                    mutate(file = gsub("(.*)_(.*)","\\2_\\1",samples)))%>%
  do.call(rbind,.)%>%
  select(hugo, chrom, pos,achange, ref_base, alt_base, file, samples, vcfinfo.alt_reads, vcfinfo.tot_reads, vaf)%>%
  mutate(gene = paste0(hugo, achange, alt_base),
         patient = gsub("(.*)_(.*_.*)_LCM.*","\\2",file))%>%
  filter(vaf > 0.05,
         vcfinfo.alt_reads > 7)

get_list <- function(rei, dat){
  mut<- dat%>%
    filter(grepl(rei,.$patient))%>%
    mutate(type = gene)%>%
    select(type, gene, file, chrom)%>%
    spread(key = file, value = gene)
  
  order = colnames(mut[,-c(1,2)])
  
  temp <- mut[,-c(1,2)]%>%
    mutate_all(function(x) ifelse(is.na(x),0,1))%>%
    unite("presence", colnames(.),sep = "", remove = F)
  summ <- lapply(unique(temp$presence), function(x) mut$type[temp$presence==x])
  names(summ) = unique(temp$presence)
  
  mut_ <- as.list(mut[,-c(1,2)])
  
  for (i in 1:length(mut_)){
    mut_[[i]] <- mut_[[i]][!is.na(mut_[[i]])]
  }
  
     
  out <- list(mut = mut_, presence = summ, order = order)
  return(out)
}

lev <- unique(xl$patient)
dat_in <- lapply(lev, function(x) get_list(x,xl))
names(dat_in) <- lev
```

# UPSETr
```{r}
upset(fromList(dat_in[[5]][[1]]), text.scale = 1.2, nsets = 100, 
      keep.order = T, sets = c(dat_in[[5]][[3]]))
```
