---
title: "IP30 analysis -- plots"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(ggmcmc)
library(gridExtra)
library(stringr)
library(fs)
library(devtools)
library(tidyverse)
library(GGally)
library(network)
library(sna)
devtools::load_all(file.path("..", "code", "clone.tools"))

outdir <- file.path("..", "output", "IP30_fixbi.Rmd")

data.dir <- file.path("..", "data")

```

```{r data}
data.file <- file.path(data.dir, "IP30_test_input.tsv")
mut.data <- read.table(data.file, sep = "\t", header = T, stringsAsFactors = F) %>%
  as_tibble()

y <- mut.data %>%
  select(sample, mut_id, y) %>%
  spread(sample, y)

n <- mut.data %>%
  select(sample, mut_id, n) %>%
  spread(sample, n)

m <- mut.data %>%
  select(sample, mut_id, m) %>%
  spread(sample, m)

tcn <- mut.data %>%
  select(sample, mut_id, tcn) %>%
  spread(sample, tcn)

S <- length(unique(mut.data$sample))
I <- length(unique(mut.data$mut_id))

input.data <- list("I" = I, "S" = S,
                   "y" = y[, 2:(S+1)], "n" = n[, 2:(S+1)],
                   "m" = m[, 2:(S+1)], "tcn" = tcn[, 2:(S+1)])
```

```{r chains}
samps.list <- readRDS(file.path(outdir, "samps.list.rds"))
K <- 14
kToTest <- 5:15
samps <- samps.list[[which(kToTest == K)]]
chains <- ggs(samps) 
z.chain <- chains[grep("z", chains$Parameter), ]
w.chain <- chains[grep("w", chains$Parameter), ]
mcmc_w <- group_by(w.chain, Parameter) %>%
    summarize(mean=mean(value))
# chains <- readRDS(file.path("output",
#                             "IP30.Rmd",
#                             "chains.rds"))

mcmc_z <- z.chain %>%
    group_by(Parameter, value) %>%
    summarize(n=n(),
              maxiter=max(Iteration)) %>%
    mutate(probability=n/maxiter)

mcf_stats <- w.chain %>%
    group_by(Parameter) %>%
    summarize(sd=sd(value),
              mean=mean(value))
map_z <- mcmc_z %>%
    group_by(Parameter) %>%
    summarize(value=value[probability==max(probability)])
##mcmc_vals <- orderW(truth, map_z)
##mcmc_w <- matrix(mcmc_vals$mean, 10, 3, byrow=TRUE)


```

# Trees results

# Posterior distribution of trees

```{r trees}
results <- readRDS(file.path("..", "output", "IP30_fixbi.Rmd", "trees.rds"))
trees <- sapply(results$admat.chain, numericRepresentation)
tab <- table(trees)
length(tab)
freq <- as.numeric(tab)
prob <- freq/sum(freq)
plot(prob)


tb <- tibble(prob = prob,
             tree = names(tab))
tb <- tb %>%
  mutate(index = match(tb$tree, trees)) 
tb <- tb %>%
  mutate(score = results$score.chain[tb$index])


tb <- tb %>%
  arrange(desc(score))
top.score.plots <- list()
for (i in 1:10) {
  adm <- admat.chain.thinned[[tb$index[i]]]
  dag <- plotDAG(adm) + 
    ggtitle(paste0("Rank ", i, 
                   ", freq = ", round(tb$prob[i], 4),
                   ", score = ", round(tb$score[i], 3)))
  top.score.plots[[i]] <- dag
}

tb <- tb %>%
  arrange(desc(prob))
top.freq.plots <- list()
for (i in 1:10) {
  adm <- results$admat.chain[[tb$index[i]]]
  dag <- plotDAG(adm) + 
    ggtitle(paste0("Rank ", i, 
                   ", freq = ", round(tb$prob[i], 4),
                   ", score = ", round(tb$score[i], 3)))
  top.freq.plots[[i]] <- dag
}

score.plots <- do.call(grid.arrange, c(top.score.plots, nrow=4))
ggsave(file.path(outdir, "top.10.score.trees.pdf"), score.plots, width = 15, height = 20)

freq.plots <- do.call(grid.arrange, c(top.freq.plots, nrow=4))
ggsave(file.path(outdir, "top.10.freq.trees.pdf"), freq.plots, width = 15, height = 20)

```
