---
title: "Simulated data -- Tree MH plots"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
library(ggmcmc)
library(gridExtra)
library(stringr)
library(fs)
library(devtools)
library(tidyverse)
library(GGally)
library(network)
library(sna)
library(pcalg)
devtools::load_all(file.path("..", "code", "clone.tools"))

outdir <- file.path("..", "output", "plot_trees.Rmd")
```

```{r read_chains}
I <- 100; K <- 10; S <- 3
set.seed(123)
test.data <- simulateData(I, K, S)
results <- readRDS(file.path("..", "output", "mh_trees_2.Rmd", "trees.rds"))
```

# thin chains

```{r}
numIter <- length(results$score.chain)

thin <- 10

thin.ind <- seq(1, numIter, length.out = round(numIter/thin, 1))

score.chain.thinned <- results$score.chain[thin.ind]

thinned.tb <- tibble(score = score.chain.thinned, 
                     iter = seq_len(length(score.chain.thinned)),
                     log.score = log(score.chain.thinned))

ggplot(thinned.tb, aes(x = iter, y = log.score)) +
  geom_line() +
  theme_light()

full.tb <- tibble(score = results$score.chain, 
                  iter = seq_len(length(results$score.chain)),
                  log.score = log(results$score.chain))
ggplot(full.tb, aes(x = iter, y = log.score)) +
  geom_line() +
  theme_light()


admat.chain.thinned <- results$admat.chain[thin.ind]
sampled.w.chain.thinned <- results$sampled.w.chain[thin.ind]
```


```{r true_tree}
chains <- readRDS(file.path("..",
                            "output",
                            "cluster_variants.Rmd",
                            "chains.rds"))
w.chain <- chains[grep("w", chains$Parameter), ]
z.chain <- chains[grep("z", chains$Parameter), ]
mcmc_z <- z.chain %>%
    group_by(Parameter, value) %>%
    summarize(n=n(),
              maxiter=max(Iteration)) %>%
    mutate(probability=n/maxiter)

mcf_stats <- w.chain %>%
    group_by(Parameter) %>%
    summarize(sd=sd(value),
              mean=mean(value))
map_z <- mcmc_z %>%
    group_by(Parameter) %>%
    summarize(value=value[probability==max(probability)])

answer <- initializeAdjacencyMatrix(mcf_stats, 0.01)
answer["root", "cluster7"] <- answer["cluster7", "cluster1"] <-
    answer["cluster1", "cluster8"] <- answer["cluster1", "cluster9"] <-
    answer["cluster8", "cluster10"] <- answer["cluster8", "cluster2"] <-
    answer["cluster10", "cluster4"] <- answer["cluster2", "cluster3"] <-
    answer["cluster9", "cluster6"] <- answer["cluster6", "cluster5"] <- 1
true.graphNEL <- as(plainAdmat(answer), "graphNEL")
```

# Posterior distribution of trees

```{r trees}
trees <- sapply(admat.chain.thinned, numericRepresentation)
tab <- table(trees)
length(tab)
freq <- as.numeric(tab)
prob <- freq/sum(freq)
plot(prob)



tb <- tibble(prob = prob,
             tree = names(tab))
tb <- tb %>%
  mutate(index = match(tb$tree, trees)) 
tb <- tb %>%
  mutate(score = score.chain.thinned[tb$index])



tree.plot.dir <- file.path(outdir, "trees")
dir_create(tree.plot.dir)

tb <- tb %>%
  arrange(desc(score))
top.score.plots <- list()
for (i in 1:10) {
  adm <- admat.chain.thinned[[tb$index[i]]]
  g <- as(plainAdmat(adm), "graphNEL")
  dag <- plotDAG(adm) + 
    ggtitle(paste0("Rank ", i, 
                   ", freq = ", round(tb$prob[i], 4),
                   ", score = ", round(tb$score[i], 3),
                   ", shd = ", shd(true.graphNEL, g)))
  top.score.plots[[i]] <- dag
}

tb <- tb %>%
  arrange(desc(prob))
top.freq.plots <- list()
for (i in 1:10) {
  adm <- admat.chain.thinned[[tb$index[i]]]
  g <- as(plainAdmat(adm), "graphNEL")
  dag <- plotDAG(adm) + 
    ggtitle(paste0("Rank ", i, 
                   ", freq = ", round(tb$prob[i], 4),
                   ", score = ", round(tb$score[i], 3),
                   ", shd = ", shd(true.graphNEL, g)))
  top.freq.plots[[i]] <- dag

}


score.plots <- do.call(grid.arrange, c(top.score.plots, nrow=4))
ggsave(file.path(tree.plot.dir, "top.10.score.trees.pdf"), score.plots, width = 15, height = 20)

freq.plots <- do.call(grid.arrange, c(top.freq.plots, nrow=4))
ggsave(file.path(tree.plot.dir, "top.10.freq.trees.pdf"), freq.plots, width = 15, height = 20)
```


```{r distance}
tb <- tb %>%
  arrange(desc(prob))
graphs <- list()
for (i in 1:10) {
  adm <- admat.chain.thinned[[tb$index[i]]]
  graph[[i]] <- as(plainAdmat(adm), "graphNEL")
}

g1 <- as(plainAdmat(admat.chain.thinned[[tb$index[1]]]), "graphNEL")
g2 <- as(plainAdmat(admat.chain.thinned[[tb$index[2]]]), "graphNEL")
shd(g1,g2)
```
